package com.maxem.game;

public enum GameMode {
    PLAYER_VS_PLAYER,
    PLAYER_VS_EASY_COMPUTER,
    PLAYER_VS_HARD_COMPUTER,
    EASY_COMPUTER_VS_EASY_COMPUTER,
    EASY_COMPUTER_VS_HARD_COMPUTER,
    HARD_COMPUTER_VS_HARD_COMPUTER
}
